cxx_binary(
  name = 'sanity',
  srcs = [
    'test_sanity.c',
  ],
  deps = [
    '//:cubeb',
  ],
)

cxx_binary(
  name = 'tone',
  srcs = [
    'test_tone.c',
  ],
  deps = [
    '//:cubeb',
  ],
)
